# Generated by Django 3.0.5 on 2020-07-06 23:17

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import my_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=my_app.models.image_file_path)),
                ('position', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Committee',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=my_app.models.image_file_path)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('bg_image', models.ImageField(blank=True, upload_to=my_app.models.image_file_path, verbose_name='Background Image')),
                ('about', models.TextField(blank=True)),
                ('about_image', models.ImageField(blank=True, upload_to=my_app.models.image_file_path, verbose_name='About Image')),
            ],
            options={
                'verbose_name_plural': 'Home',
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=my_app.models.image_file_path)),
                ('player_type', models.CharField(choices=[('M', 'Medalist'), ('B', 'Black Belt'), ('P', 'Player')], max_length=1, verbose_name='Player Type')),
                ('description', ckeditor.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=my_app.models.image_file_path)),
                ('description', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_details', to='my_app.Events')),
            ],
            options={
                'verbose_name_plural': 'Event Details',
            },
        ),
    ]
