# Generated by Django 3.0.5 on 2020-07-06 20:06

from django.db import migrations, models
import my_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('bg_image', models.ImageField(upload_to=my_app.models.image_file_path, verbose_name='Background Image')),
                ('about', models.TextField()),
                ('about_image', models.ImageField(upload_to=my_app.models.image_file_path, verbose_name='About Image')),
            ],
        ),
    ]
