# Generated by Django 3.0.5 on 2020-07-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
