# Generated by Django 3.0.5 on 2020-07-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20200707_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
