# Generated by Django 3.0.5 on 2020-07-07 13:17

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20200707_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', embed_video.fields.EmbedVideoField(verbose_name='Video Link')),
                ('description', models.CharField(max_length=255, verbose_name='Video Description')),
            ],
        ),
    ]
