# Generated by Django 3.0.5 on 2020-07-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_contact_videos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='players',
            options={'ordering': ['player_type'], 'verbose_name_plural': 'Players'},
        ),
        migrations.AlterField(
            model_name='players',
            name='player_type',
            field=models.CharField(choices=[('medalist', 'Medalist'), ('black_belt', 'Black Belt'), ('player', 'Player')], max_length=12, verbose_name='Player Type'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='description',
            field=models.TextField(verbose_name='Video Description'),
        ),
    ]
