# Generated by Django 3.0.5 on 2020-07-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_auto_20200707_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
