# Generated by Django 3.0.5 on 2020-07-08 20:29

from django.db import migrations, models
import my_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_auto_20200708_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=my_app.models.image_file_path)),
            ],
            options={
                'verbose_name_plural': 'ImageSlider',
            },
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name_plural': 'Videos'},
        ),
        migrations.AddField(
            model_name='home',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
