# Generated by Django 3.0.5 on 2020-07-09 10:00

from django.db import migrations, models
import my_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_auto_20200708_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=my_app.models.image_file_path),
        ),
    ]
