# Generated by Django 3.0.5 on 2020-07-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_auto_20200709_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_one', models.CharField(blank=True, max_length=17, verbose_name='Phone Number 1')),
                ('phone_two', models.CharField(blank=True, max_length=17, verbose_name='Phone Number 2')),
                ('email', models.EmailField(max_length=70, verbose_name='Email Address')),
            ],
            options={
                'verbose_name_plural': 'Contact',
            },
        ),
    ]
