# Generated by Django 3.0.5 on 2020-07-12 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_auto_20200710_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='committee',
            options={'ordering': ['-position'], 'verbose_name_plural': 'Committee'},
        ),
        migrations.AlterModelOptions(
            name='players',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Players'},
        ),
    ]
